### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by krsamue101** [itsrafsanjani/laravel-instagram-clone#10]
Hi! Thanks you for making this as open source but
I get 500 Internal Server Error when I try to connect.
my site is https://~~~~.xyz/gicstagram And
```
root@instance-1:/var/www/html/gicstagram# ls
backend  build  css  favicon.ico  images  index.php  installer  js  robots.txt  svg  vendor
root@instance-1:/var/www/html/gicstagram# 
```
How to solve this?
Thanks!

**Comment by itsrafsanjani** [comment]
Did you configure the `.env` file with the correct credentials?

**Comment by krsamue101** [comment]
Is there any problem?
`
APP_NAME="GicsTagram" APP_ENV=local APP_KEY= APP_DEBUG=false APP_URL=https://mydomain.com/instaclone
FORCE_HTTPS=true APP_LOCALE=en LOG_CHANNEL=stack DB_CONNECTION=mariadb DB_HOST=127.0.0.1 DB_PORT=3306 DB_DATABASE=laravel_instagram_clone DB_USERNAME=root DB_PASSWORD=ksme4001! BROADCAST_DRIVER=log CACHE_DRIVER=file QUEUE_CONNECTION=sync SESSION_DRIVER=file SESSION_LIFETIME=120 REDIS_HOST=127.0.0.1 REDIS_PASSWORD=null 
REDIS_PORT=6379 MAIL_MAILER=smtp MAIL_HOST=smtp.gmail.com MAIL_PORT=1587 MAIL_USERNAME=mygmail@gmail.com MAIL_PASSWORD=My gmail password
MAIL_ENCRYPTION=tls 
AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= AWS_DEFAULT_REGION=us-east-1 AWS_BUCKET= PUSHER_APP_ID= PUSHER_APP_KEY= PUSHER_APP_SECRET= PUSHER_APP_CLUSTER= VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}" VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}" DEBUGBAR_ENABLED=false QUERY_DETECTOR_ENABLED=false # ################################################################################## # ## 'filesystem' and 'media library' disk should be same ### # ################################################################################## # filesystem disk FILESYSTEM_DRIVER=public # Spatie Media Library MEDIA_DISK=public # Cloudinary CLOUDINARY_API_KEY= CLOUDINARY_API_SECRET= CLOUDINARY_CLOUD_NAME= CLOUDINARY_SECURE= # Sightengine SIGHTENGINE_USER= SIGHTENGINE_SECRET= # Chatify CHATIFY_ROUTES_PREFIX=messages CHATIFY_NAME=Laragram CHATIFY_MAX_FILE_SIZE=157286400 # ENVATO ENVATO_PERSONAL_TOKEN= ENVATO_PURCHASE_CODE= # Github Profile Link GITHUB_PROFILE_LINK=https://github.com/itsrafsanjani VITE_GITHUB_PROFILE_LINK="${GITHUB_PROFILE_LINK}" # Github Repository Link GITHUB_REPO_LINK=https://github.com/itsrafsanjani/laravel-instagram-clone VITE_GITHUB_REPO_LINK="${GITHUB_REPO_LINK}" # sslcommerz configuration SSLC_STORE_ID= SSLC_STORE_PASSWORD= SSLC_STORE_CURRENCY=BDT SSLC_ROUTE_SUCCESS=payment.success SSLC_ROUTE_FAILURE=payment.failure SSLC_ROUTE_CANCEL=payment.cancel SSLC_ROUTE_IPN=payment.ipn SSLC_ALLOW_LOCALHOST=true SSLC_SANDBOX=true
`

**Comment by krsamue101** [comment]
Is there any problem?
`
APP_NAME="GicsTagram"
APP_ENV=local
APP_KEY=
APP_DEBUG=false
APP_URL=https://mydomain.com/gicstagram
FORCE_HTTPS=true
APP_LOCALE=en

LOG_CHANNEL=stack

DB_CONNECTION=mariadb
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=laravel_instagram_clone
DB_USERNAME=root
DB_PASSWORD=mypassword

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=1587
MAIL_USERNAME=mail@gmail.com
MAIL_PASSWORD=mypassword001!
MAIL_ENCRYPTION=tls

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=

VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

DEBUGBAR_ENABLED=false
QUERY_DETECTOR_ENABLED=false

# ##################################################################################
# ##             'filesystem' and 'media library' disk should be same            ###
# ##################################################################################

# filesystem disk
FILESYSTEM_DRIVER=public

# Spatie Media Library
MEDIA_DISK=public

# Cloudinary
CLOUDINARY_API_KEY=
CLOUDINARY_API_SECRET=
CLOUDINARY_CLOUD_NAME=
CLOUDINARY_SECURE=

# Sightengine
SIGHTENGINE_USER=
SIGHTENGINE_SECRET=

# Chatify
CHATIFY_ROUTES_PREFIX=messages
CHATIFY_NAME=Laragram
CHATIFY_MAX_FILE_SIZE=157286400

# ENVATO
ENVATO_PERSONAL_TOKEN=
ENVATO_PURCHASE_CODE=

# Github Profile Link
GITHUB_PROFILE_LINK=https://github.com/itsrafsanjani
VITE_GITHUB_PROFILE_LINK="${GITHUB_PROFILE_LINK}"

# Github Repository Link
GITHUB_REPO_LINK=https://github.com/itsrafsanjani/laravel-instagram-clone
VITE_GITHUB_REPO_LINK="${GITHUB_REPO_LINK}"

# sslcommerz configuration
SSLC_STORE_ID=
SSLC_STORE_PASSWORD=
SSLC_STORE_CURRENCY=BDT
SSLC_ROUTE_SUCCESS=payment.success
SSLC_ROUTE_FAILURE=payment.failure
SSLC_ROUTE_CANCEL=payment.cancel
SSLC_ROUTE_IPN=payment.ipn
SSLC_ALLOW_LOCALHOST=true
SSLC_SANDBOX=true
`

**Comment by itsrafsanjani** [comment]
You are missing `APP_KEY` run `php artisan key:generate` and make `APP_DEBUG=true` to see the error.

**Comment by itsrafsanjani** [comment]
For database run `php artisan migrate --seed` that will migrate the database and add som dummy data.

**Comment by krsamue101** [comment]
Now I get `Uncaught Error: Permission denied to access property "unlock"` in console. And still I get 500 Error

**Comment by krsamue101** [comment]
I set APP_DEBUG to true and I see nothing.

**Comment by krsamue101** [comment]
I ran `php artisan migrate --seed `
```
  Database connection [mariadb] not configured.
```

**Comment by krsamue101** [comment]
It looked like this doesn't support mariadb. And I changed to mysql but still not working

**Comment by itsrafsanjani** [comment]
What kind of error are you facing now? `APP_DEBUG=true` should show the error message on the webpage.

**Comment by krsamue101** [comment]
Yes. `APP_DEBUG` is true and I see nothing. But should I put only public folder on /var/www/html? or should I put project root folder?

**Comment by itsrafsanjani** [comment]
Put everything to `/var/www/html` and use NGINX or Apache to locate the public folder. Check this for example: [https://laravel.com/docs/9.x/deployment#nginx](https://laravel.com/docs/9.x/deployment#nginx)

**Comment by krsamue101** [comment]
what php version is recommanded to use?

**Comment by krsamue101** [comment]
Now I see
```
The stream or file "/var/www/html/gicstagram/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/gicstagram/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/gicstagram/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/gicstagram/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/gicstagram/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/gicstagram/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/gicstagram/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/gicstagram/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/gicstagram/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/gicstagram/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/gicstagram/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/gicstagram/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/gicstagram/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: The stream or file "/var/www/html/gicstagram/storage/logs/laravel.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: file_put_contents(/var/www/html/gicstagram/storage/framework/sessions/ryjYubP8Ke887TdbkzNpNDaWdUYHQWwmoqAiIYR5): Failed to open stream: Permission denied Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}} Context: {"exception":{}}```

**Comment by krsamue101** [comment]
I fixed it and it couldn't load assets. These app.72f49e37.css, app.f31eb975.js gives me 404 error

**Comment by krsamue101** [comment]
I'm running this with apache2.

When I tries to post comment, likes, or etc.. 
It sends post request to http://127.0.0.1/comments and get 404 not found what should i do

**Comment by itsrafsanjani** [comment]
Sorry but I think you need to learn some basic Laravel to run this application. You can check [laracasts.com](laracasts.com) and Laravel's official documentation.
